all_places = [
        "A rooftop bar",
        "A comedy club",
        "A concert venue",
        "A music festival",
        "A street fair",
        "A bowling alley",
        "A casino",
        "A sports stadium",
        "A karaoke bar",
        "A restaurant with live music",
        "A rooftop terrace",
        "A beach bonfire",
        "A drive-in movie theater",
        "A laser tag arena",
        "A trampoline park",
        "An escape room",
        "A miniature golf course",
        "A rock climbing gym",
        "A go-kart track",
        "A bowling alley",
        "A comedy club",
        "A concert hall",
        "A music festival",
        "A street festival",
        "A rooftop pool",
        "A rooftop garden",
        "A lounge",
        "A dance club",
        "A public square",
        "A rooftop yoga class",
        "A ammusement park",
        "A water park",
        "A ammunation facility",
        "A shooting range",
        "A paintball arena",
        "A go-kart track",
        "SSN College of Engineering",
        "IIT Madras"]